spring:
    profiles:
      active:
      - dev
---

spring:
    profiles: dev  #开发环境
    application:
          name: cloud-dept-dev
---

spring:
    profiles: test #测试环境
    appkication:
        name: cloud-dept-test
#请保存为UTF-8格式
